
name: HorseCI Added Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display Go version
        run: go version
      - name: Run unit tests
        run: go test -race -vet=off ./...
